const KEY='machineServiceLogV01';
const defaultData={manufacturers:['Husqvarna','Wacker Neuson','Allen Engineering','Somero','Multiquip'],machineTypes:['Concrete Saw','Ride-On Trowel','Walk-Behind Trowel','Power Buggy','Screed','Grinder','Generator'],companies:[],models:[],machines:[],services:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||defaultData;
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const $=id=>document.getElementById(id); const today=()=>new Date().toISOString().slice(0,10);
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function fillSelect(id,items,placeholder){$(id).innerHTML='<option value="">'+placeholder+'</option>'+items.map(x=>`<option>${esc(x)}</option>`).join('');}
function renderSelects(){fillSelect('manufacturer',data.manufacturers,'Select manufacturer');fillSelect('machineType',data.machineTypes,'Select machine type');fillSelect('company',data.companies,'Select company');fillSelect('newModelM',data.manufacturers,'Manufacturer');fillSelect('newModelT',data.machineTypes,'Machine type');}
function render(){renderSelects();renderDashboard();renderMachines();renderPresets();}
function renderDashboard(){ $('machineCount').textContent=data.machines.length; const active=data.machines.filter(m=>m.status!=='Complete').length; $('activeCount').textContent=active; $('hoursCount').textContent=data.services.reduce((s,x)=>s+Number(x.hours||0),0).toFixed(2); const recent=[...data.services].sort((a,b)=>b.workDate.localeCompare(a.workDate)).slice(0,8); $('recentList').innerHTML=recent.length?recent.map(serviceHTML).join(''):'<div class="muted">No service records yet.</div>'; }
function renderMachines(){let q=($('machineSearch')?.value||'').toLowerCase();let arr=data.machines.filter(m=>Object.values(m).join(' ').toLowerCase().includes(q));$('machineList').innerHTML=arr.length?arr.map(m=>`<div class="item" onclick="showMachine('${m.id}')"><div class="itemtop"><strong>${esc(m.unit)}</strong><span class="badge">${esc(m.status)}</span></div><div class="muted">${esc(m.manufacturer||'')} ${esc(m.model||'')} · ${esc(m.machineType||'')}</div><div class="muted">Last engine hours: ${m.engineHours||'—'} · ${esc(m.company||'')}</div></div>`).join(''):'<div class="muted">No machines found.</div>';}
function serviceHTML(s){return `<div class="item" onclick="showMachine('${s.machineId}')"><div class="itemtop"><strong>${esc(s.unit)}</strong><span class="badge">${esc(s.workDate)}</span></div><div>${esc(s.workDescription)}</div><div class="muted">${s.hours} labor hours · engine ${s.engineHours||'—'}</div></div>`}
function renderPresets(){[['manufacturers','manufacturersList'],['machineTypes','typesList'],['companies','companiesList']].forEach(([k,id])=>$(id).innerHTML=data[k].map((x,i)=>`<div class="presetitem"><span>${esc(x)}</span><button class="secondary" onclick="removePreset('${k}',${i})">×</button></div>`).join('')||'<div class="muted">None yet.</div>');$('modelsList').innerHTML=data.models.map((m,i)=>`<div class="modelrow"><strong>${esc(m.model)}</strong><span>${esc(m.manufacturer)}</span><span>${esc(m.machineType)}</span><span>${esc(m.template||'')}</span><button class="secondary" onclick="removeModel(${i})">×</button></div>`).join('')||'<div class="muted">No model rules yet.</div>';}
function addPreset(k,id){let v=$(id).value.trim();if(!v)return;if(!data[k].includes(v))data[k].push(v);$(id).value='';save();render();toast('Preset added');}
function removePreset(k,i){data[k].splice(i,1);save();render();}
function addModel(){let model=$('newModel').value.trim(),manufacturer=$('newModelM').value,machineType=$('newModelT').value,template=$('newTemplate').value.trim();if(!model)return toast('Model number is required');data.models=data.models.filter(x=>x.model.toLowerCase()!==model.toLowerCase());data.models.push({model,manufacturer,machineType,template});save();$('newModel').value='';$('newTemplate').value='';render();toast('Model rule saved');}
function removeModel(i){data.models.splice(i,1);save();render();}
$('unit').addEventListener('blur',()=>loadKnownUnit($('unit').value));$('model').addEventListener('input',()=>autoFillModel($('model').value));$('machineSearch').addEventListener('input',renderMachines);
function autoFillModel(v){let m=data.models.find(x=>x.model.toLowerCase()===v.trim().toLowerCase());if(m){$('manufacturer').value=m.manufacturer;$('machineType').value=m.machineType;$('unitHint').textContent=`Auto-filled: ${m.manufacturer} · ${m.machineType}${m.template?' · Inspection: '+m.template:''}`;}else $('unitHint').textContent='';}
function loadKnownUnit(v){let m=data.machines.find(x=>x.unit.toLowerCase()===v.trim().toLowerCase());if(!m)return;$('model').value=m.model||'';$('manufacturer').value=m.manufacturer||'';$('machineType').value=m.machineType||'';$('serial').value=m.serial||'';$('company').value=m.company||'';$('description').value=m.description||'';$('unitHint').textContent=`Existing unit found. Last engine hours: ${m.engineHours||'—'}`;}
$('date').value=today();$('workDate').value=today();
$('serviceForm').onsubmit=e=>{e.preventDefault();let unit=$('unit').value.trim();let existing=data.machines.find(m=>m.unit.toLowerCase()===unit.toLowerCase());let machine=existing||{id:crypto.randomUUID(),unit};Object.assign(machine,{model:$('model').value.trim(),manufacturer:$('manufacturer').value,machineType:$('machineType').value,serial:$('serial').value.trim(),company:$('company').value,engineHours:Number($('engineHours').value||0),description:$('description').value,status:'Active',updatedAt:today()});if(!existing)data.machines.push(machine);else Object.assign(existing,machine);data.services.push({id:crypto.randomUUID(),machineId:machine.id,unit,workDate:$('workDate').value,hours:Number($('hours').value),engineHours:Number($('engineHours').value||0),workDescription:$('workDescription').value.trim(),dateReceived:$('date').value});save();toast('Service visit saved');e.target.reset();$('date').value=today();$('workDate').value=today();$('unitHint').textContent='';setTimeout(()=>showMachine(machine.id),350);};
function showMachine(id){let m=data.machines.find(x=>x.id===id);if(!m)return;let hs=data.services.filter(s=>s.machineId===id).sort((a,b)=>b.workDate.localeCompare(a.workDate));$('detailContent').innerHTML=`<button class="secondary back" onclick="showView('machines')">← Back</button><div class="hero"><div><h2>${esc(m.unit)}</h2><p>${esc(m.manufacturer||'')} ${esc(m.model||'')} · ${esc(m.machineType||'')}</p></div><span class="badge">${esc(m.status)}</span></div><div class="cards"><div class="card"><b>${m.engineHours||'—'}</b><span>Current Engine Hours</span></div><div class="card"><b>${hs.reduce((s,x)=>s+Number(x.hours||0),0).toFixed(2)}</b><span>Total Labor Hours</span></div><div class="card"><b>${hs.length}</b><span>Service Visits</span></div></div><div class="panel"><h3>Machine Details</h3><p><b>Serial:</b> ${esc(m.serial||'—')}</p><p><b>Company:</b> ${esc(m.company||'—')}</p><p><b>Description:</b> ${esc(m.description||'—')}</p></div><div class="panel"><h3>Service History</h3><div class="history">${hs.length?hs.map(s=>`<div class="servicecard"><div class="itemtop"><strong>${esc(s.workDate)}</strong><span>${s.hours} hrs</span></div><p>${esc(s.workDescription)}</p><div class="muted">Engine hours: ${s.engineHours||'—'} · Received: ${s.dateReceived||'—'}</div></div>`).join(''):'<div class="muted">No service history.</div>'}</div></div>`;showView('detail');}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function toast(s){let t=$('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};
render();
